### PR TITLE
deps: update for strapi v5

### PR DESCRIPTION
**Pull request by Xaz16**
Hello!
We are using your bunny net provider and want to update to strapi v5. Looks like yours peer deps are outdated. Could you check this pull request please? And publish new version with new strapi version

### CODE REVIEW

**Comment by shestakov-railways** [comment]
Do need this as well

**Comment by jzambrano12** [comment]
Changes accepted!

**Comment by sehrish30** [comment]
When can we expect an update? this is blocking us from moving to v5

**Comment by shestakov-railways** [comment]
I spoted we updated it here, but not in npm
https://www.npmjs.com/package/@nexide/strapi-provider-bunny?activeTab=code
image

@jzambrano12 is there something we can do with it?

**Comment by jzambrano12** [comment]
No, my apologies. I'm uploading the repo to NPM now.

### UPDATE ###

image

**Pull request merged**
